### ISSUE TITLE
VEC Infinity 3 USB Footpedal not recognized..

### ISSUE THREAD

**Issue by Nexu6** [fairfieldt/Biped#2] opened 2021-02-07 13:57 UTC
Managed to set this up for Time Crisis 5 with AHK. However, I can't get it to work with Mame. In the mame option screen I can see it still working, because by pressing a pedal, a letter I bind to one of the pedals is shown in the "search for game.." area. If I try to bind a key for a special game, there is no reaction to a pressed pedal. Maybe I have to check an option, but can't figure it out. In the pcsx2 emulator it doesn't show up as a "vec device" as well, only as a "DX keyboard". Did I miss something? Maybe the 3. version isn't compatible with mame or pcsx2?

**Comment by johnnyruz** [comment] 2021-02-10 15:48
It doesn't sound like this is an issue with the Biped application if the pedal is successfully detected and is mapping button presses correctly for games like TC5 and in other applications. I assume you can "type" in Notepad with the key bindings setup in Biped? If that's the case then it sounds like something odd with PCSX2 and MAME and not Biped which seems to be detecting and mapping correctly. Unfortunately I don't have a v3 pedal to test.

**Comment by fairfieldt** [comment] 2021-02-10 20:28
Agree with @johnnyruz - it sounds like the issue is probably outside of Biped if it works for some applications and not others. 

I tried the latest mame64 release and input works for me.

I'm going to close this for now - happy to investigate more if it becomes clear there's an issue in Biped.

**Closed as completed by fairfieldt** 2021-02-10 20:28 UTC
